### ISSUE TITLE
Proxy /stats endpoint 404

### ISSUE THREAD

**Issue by tpccdaniel** [scrapinghub/crawlera-headless-proxy#1]
**config.toml**
proxy_api_ip = "0.0.0.0"
proxy_api_port = 3130

$ curl -x 0.0.0.0:3130 -i -H "Accept: application/json" -H "Content-Type: application/json" http://stats

**Returns**
>> 404 page not found

**Comment by 9seconds** [comment]
You do not need to pass `-x`. `-x` is for proxy interface but API is just a generic HTTP service. Correct curl is `curl -i -H "Accept: application/json" -H "Content-Type: application/json" http://<your ip address>/stats`

**Comment by 9seconds** [comment]
Please reopen if you still have a problem.
