### ISSUE TITLE
Unable to install tool using Go

### ISSUE THREAD

**Issue by jeremy-doyle** [scrapinghub/crawlera-headless-proxy#10]
I am trying to install the tool with Go as explained here:
[https://support.scrapinghub.com/support/solutions/articles/22000234854-how-to-use-crawlera-with-headless-browsers](url)

However, when I try this, the tool fails to install:
<pre>C:\Users\user1234>go get github.com/scrapinghub/crawlera-headless-proxy
# github.com/scrapinghub/crawlera-headless-proxy
go\src\github.com\scrapinghub\crawlera-headless-proxy\main.go:205:19: undefined: DefaultCertCA
go\src\github.com\scrapinghub\crawlera-headless-proxy\main.go:206:16: undefined: DefaultPrivateKey

C:\Users\user1234>crawlera-headless-proxy -c crawler\config\file.toml
'crawlera-headless-proxy' is not recognized as an internal or external command,
operable program or batch file.</pre>

**Comment by 9seconds** [comment]
Seems that these instructions are not correct. We'll fix them, thanks. Meanwhile, instructions in the current readme are up to date.
