### ISSUE TITLE
Unsafe requests

### ISSUE THREAD

**Issue by CAIOHOBORGHI** [scrapinghub/crawlera-headless-proxy#17]
Crawlera headless proxy is blocking some of my requests with the error 503... When entering the page via browser, I see a warning page of insecure request but there's the option to ignore the warning and continue.

Is there a way to configure this with crawlera headless proxy?

**Comment by 9seconds** [comment]
Yes, you need to install its https://github.com/scrapinghub/crawlera-headless-proxy/blob/master/ca.crt as a root certificate
