### ISSUE TITLE
Docker image not getting the certificate route

### ISSUE THREAD

**Issue by JoseWhiteHawk** [scrapinghub/crawlera-headless-proxy#18]
Hello,

I am trying to use the "-l" option in order to setup the certificate, but this is not working. Is there any issue regarding this?

Thank you in advance.

Cheers.

**Comment by 9seconds** [comment]
Sorry for the delay. Could you please tell how you start container?

**Comment by 9seconds** [comment]
I close this ticket. Feel free to reopen if you haven't found an answer
