### ISSUE TITLE
Unauthorized Crawlera Header

### ISSUE THREAD

**Issue by phrfpeixoto** [scrapinghub/crawlera-headless-proxy#22]
HI,

Current Crawlera plans Basic and Advanced are unable to use the provided Docker image without changing its *config.toml* file.

The default config file includes the "X-Crawelera-Cookies: disable" header, that is no now only available on the Enterprise tier.

**Comment by 9seconds** [comment]
Well, I see no problems in providing their own configuration file to a docker image. It is possible to mount your own file with `-v` flag ¯\_(ツ)_/¯
