### ISSUE TITLE
Proxy Service Crashes

### ISSUE THREAD

**Issue by gcallsen** [scrapinghub/crawlera-headless-proxy#3]
Greetings,

We're using this service running in a docker container (running `scrapinghub/crawlera-headless-proxy:latest`). It works properly for some period of time and then will fail with:

```
time="2019-02-01T07:58:55Z" level=debug msg="Layer trace" execute-duration=35.96716655s on-request-durations="[60.778µs 5.812005ms 6.894µs 20.544µs 25.788µs]" on-request-error="<nil>" on-response-durations="[45.852µs 345ns 0s 396ns 2.394µs]" request-id=987636319649793
panic: Length of args %!= 2

goroutine 261844 [running]:
github.com/scrapinghub/crawlera-headless-proxy/proxy.(*Logger).getFields(0xded598, 0xc008849c80, 0x3, 0x3, 0xc004653e88)
	/app/proxy/logger.go:38 +0x18d
github.com/scrapinghub/crawlera-headless-proxy/proxy.(*Logger).Warn(0xded598, 0x9ab433, 0x2a, 0xc008849c80, 0x3, 0x3)
	/app/proxy/logger.go:22 +0x6c
github.com/9seconds/httransform.(*Server).makeHijackHandler.func1(0xa2d6a0, 0xc00254c180)
	/go/pkg/mod/github.com/9seconds/httransform@v0.0.0-20190111135017-ebcb54ac3762/server.go:104 +0x510
github.com/valyala/fasthttp.hijackConnHandler(0xa24a40, 0xc0035ac540, 0xa2d880, 0xc0025240c0, 0xc000240680, 0xc00302a780)
	/go/pkg/mod/github.com/valyala/fasthttp@v1.1.0/server.go:2086 +0x7b
created by github.com/valyala/fasthttp.(*Server).serveConn
	/go/pkg/mod/github.com/valyala/fasthttp@v1.1.0/server.go:2005 +0xb95
```

When this happens, the service hangs at this message and will not handle any new requests.

Restarting the service will result in it immediately handling requests as expected.

We have not as yet found any specific trigger to reproduce the error. Average request rate should not be exceeding ~1 request per second with occasional bursts up to ~16/s (though will verify that). This seems to be happening inside ~60 minutes or so after sustained use.

We will continue to debug in terms of whether we can find a reproducible scenario, any help is greatly appreciated.

Thanks!

**Comment by 9seconds** [comment]
Thanks for the report! I'll fix as soon as possible

**Comment by 9seconds** [comment]
Should be fixed now, thanks!
