### ISSUE TITLE
Work with Selenium

### ISSUE THREAD

**Issue by RobertHWChiangSV** [scrapinghub/crawlera-headless-proxy#4]
Hi,

I find two `Selenium` examples from README.md and examples/selenium/run-example.py.
`Selenium` standalone server is a requirement for `crawlera-headless-proxy`？

If i don't use standalone server, `response_code` from `crawlera-headless-proxy` would be 407.
```shell
$ crawlera-headless-proxy -a "apikey" -x profile=desktop -x cookies=disable --debug
DEBU[0000] Listen on 127.0.0.1:3128                      adblock-lists="[]" apikey=apikey bindip=127.0.0.1 bindport=3128 concurrent-connections=0 crawlera-host=proxy.crawlera.com crawlera-port=8010 debug=true dont-verify-crawlera-cert=false no-auto-sessions=false proxy-api-ip=127.0.0.1 proxy-api-port=3129 xheaders="map[X-Crawlera-Cookies:disable X-Crawlera-Profile:desktop]"

INFO[0065] New request                                   client_id=client_id method=GET remote_addr="127.0.0.1:51496" request_id=8589934593 url="https://scrapinghub.com/"
WARN[0066] Could not obtain new session even after retry 
INFO[0066] Finish request                                client_id=client_id error="<nil>" method=GET remote_addr="127.0.0.1:51496" request_id=8589934593 response_code=407 url="https://scrapinghub.com/"
DEBU[0066] Layer trace: request-id 0x200000001, on-request-durations []time.Duration{82074, 7070, 30930, 45151}, execute-duration 996916402, on-response-durations []time.Duration{33305, 211, 527, 834059480}, on-request-error <nil> 
```

**Comment by 9seconds** [comment]
Hi. This is absolutely not a requirement. I guess you have a problem because of unspecified API key. From logs, I see that you use literally `apikey` string. Please pass your own Crawlera key.

**Comment by RobertHWChiangSV** [comment]
I just don't want to paste real Crawlera API KEY, so I use `apikey` string instead 😆 

Crawlera support engineer answered my question, the problem is `X-Crawlera-Profile` is only available for greater than C10 plan.
https://support.scrapinghub.com/public/tickets/711b3101d5a6a35117ea5984b69a4f30f4dba3216868aef92f82ab3ab5a83bd9

Thanks. This issue should be closed.
