### ISSUE TITLE
Request failed even after retry

### ISSUE THREAD

**Issue by ktmohammedsulaim** [scrapinghub/crawlera-headless-proxy#92]
![image](https://user-images.githubusercontent.com/112069495/234830434-51ab7f4a-bebe-49b3-9b9c-e57107a1f701.png)
I'm getting this error when trying to navigate from page to another page using puppeteer. Any solution?

**Comment by storymode7** [comment]
Hi @ktmohammedsulaim , could you share the script you are using?

**Comment by ktmohammedsulaim** [comment]
@storymode7 Thanks for the response. Actually I was using local proxy server with Puppeteer. Now, after getting touch in with support team I migrated to Zyte API which seems works fine.
